<?php

/**
 * This is the model base class for the table "novidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Novidade".
 *
 * Columns in table "novidade" available as properties of the model,
 * followed by relations of table "novidade" available as properties of the model.
 *
 * @property integer $idnovidade
 * @property string $data
 * @property integer $categoria_idcategoria
 * @property string $titulo
 * @property string $texto
 * @property string $imagem
 * @property integer $gallery_id
 * @property string $ativo
 *
 * @property Categoria $categoria
 * @property Gallery $gallery
 */
abstract class BaseNovidade extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'novidade';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Novidade|Novidades', $n);
	}

	public static function representingColumn() {
		return array('titulo');
	}

	public function rules() {
		return array(
			array('categoria_idcategoria, gallery_id', 'required'),
			array('categoria_idcategoria, gallery_id', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>100),
			array('imagem', 'length', 'max'=>140),
			array('ativo', 'length', 'max'=>1),
			array('data, texto', 'safe'),
			array('data, titulo, texto, imagem, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idnovidade, data, categoria_idcategoria, titulo, texto, imagem, gallery_id, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'categoria' => array(self::BELONGS_TO, 'Categoria', 'categoria_idcategoria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idnovidade' => Yii::t('app', 'Idnovidade'),
			'data' => Yii::t('app', 'Data'),
			'categoria_idcategoria' => Yii::t('app', 'Categoria'),
			'titulo' => Yii::t('app', 'Título'),
			'texto' => Yii::t('app', 'Texto'),
			'imagem' => Yii::t('app', 'Imagem'),
			'gallery_id' => Yii::t('app', 'Galeria de fotos'),
			'ativo' => Yii::t('app', 'Ativo'),
			'categoria' => Yii::t('app', 'Categoria'),
			'gallery' => Yii::t('app', 'Galeria de fotos'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->compare('idnovidade', $this->idnovidade);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('categoria_idcategoria', $this->categoria_idcategoria);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('gallery_id', $this->gallery_id);
		$criteria->compare('ativo', $this->ativo, true);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}