<?php

/**
 * This is the model base class for the table "perfil_acesso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PerfilAcesso".
 *
 * Columns in table "perfil_acesso" available as properties of the model,
 * followed by relations of table "perfil_acesso" available as properties of the model.
 *
 * @property integer $idperfil_acesso
 * @property integer $idperfil
 * @property integer $idcategoria
 * @property string $ativo
 *
 * @property ModuloCategoria $moduloCategoria
 * @property Perfil $perfil
 */
abstract class BasePerfilAcesso extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'perfil_acesso';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Acesso|Acessos', $n);
	}

	public static function representingColumn() {
		return array('ativo');
	}

	public function rules() {
		return array(
			array('idperfil, idcategoria', 'required'),
			array('idperfil, idcategoria', 'numerical', 'integerOnly'=>true),
			array('ativo', 'length', 'max'=>1),
			array('ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idperfil_acesso, idperfil, idcategoria, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'moduloCategoria' => array(self::BELONGS_TO, 'ModuloCategoria', 'idcategoria'),
			'perfil' => array(self::BELONGS_TO, 'Perfil', 'idperfil'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idperfil_acesso' => Yii::t('app', 'Idperfil Acesso'),
			'idperfil' => null,
			'idcategoria' => null,
			'ativo' => Yii::t('app', 'Ativo'),
			'moduloCategoria' => null,
			'perfil' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idperfil_acesso', $this->idperfil_acesso);
		$criteria->compare('idperfil', $this->idperfil);
		$criteria->compare('idcategoria', $this->idcategoria);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
