<?php

/**
 * This is the model base class for the table "modulo_categoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ModuloCategoria".
 *
 * Columns in table "modulo_categoria" available as properties of the model,
 * followed by relations of table "modulo_categoria" available as properties of the model.
 *
 * @property integer $idcategoria
 * @property integer $idmodulo
 * @property string $nome
 * @property integer $posicao
 * @property string $icone
 * @property string $descricao
 * @property string $url
 * @property string $ativo
 *
 * @property Modulo $modulo
 * @property ModuloSubcategoria[] $moduloSubcategorias
 * @property PerfilAcesso[] $perfilAcessos
 */
abstract class BaseModuloCategoria extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'modulo_categoria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Categoria|Categorias', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('idmodulo', 'required'),
			array('idmodulo, posicao', 'numerical', 'integerOnly'=>true),
			array('nome, url', 'length', 'max'=>100),
			array('icone', 'length', 'max'=>160),
			array('ativo', 'length', 'max'=>1),
			array('descricao', 'safe'),
			array('nome, posicao, icone, descricao, url, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idcategoria, idmodulo, nome, posicao, icone, descricao, url, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'modulo' => array(self::BELONGS_TO, 'Modulo', 'idmodulo'),
			'moduloSubcategorias' => array(self::HAS_MANY, 'ModuloSubcategoria', 'idcategoria'),
			'perfilAcessos' => array(self::HAS_MANY, 'PerfilAcesso', 'idcategoria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idcategoria' => Yii::t('app', 'Idcategoria'),
			'idmodulo' => null,
			'nome' => Yii::t('app', 'Nome'),
			'posicao' => Yii::t('app', 'Posicao'),
			'icone' => Yii::t('app', 'Icone'),
			'descricao' => Yii::t('app', 'Descricao'),
			'url' => Yii::t('app', 'Url'),
			'ativo' => Yii::t('app', 'Ativo'),
			'modulo' => null,
			'moduloSubcategorias' => null,
			'perfilAcessos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idcategoria', $this->idcategoria);
		$criteria->compare('idmodulo', $this->idmodulo);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('posicao', $this->posicao);
		$criteria->compare('icone', $this->icone, true);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
