<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * followed by relations of table "usuario" available as properties of the model.
 *
 * @property integer $idusuario
 * @property integer $idperfil
 * @property string $nome
 * @property string $cpf
 * @property string $email
 * @property string $telefone
 * @property string $senha
 * @property string $ativo
 *
 * @property ModuloDownload[] $moduloDownloads
 * @property Perfil $perfil
 * @property UsuarioRecuperasenha[] $usuarioRecuperasenhas
 */
abstract class BaseUsuario extends GxActiveRecord {

	public $senha_confirma;


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('idperfil, nome, cpf', 'required'),
			array('email', 'email'),
			array('idperfil', 'numerical', 'integerOnly'=>true),
			array('nome, cpf, email, telefone, senha', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('nome, cpf, email, telefone, senha, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idusuario, idperfil, nome, cpf, email, telefone, senha, ativo', 'safe', 'on'=>'search'),
			//Campos obrigatórios
			array('senha,senha_confirma', 'required', 'on'=>'insert'),

			array('cpf', 'unique',  'criteria' => array(
				'condition' => "idusuario != '".$this->idusuario."'",
			)),

			//Campos que devem ser iguais
			array('senha','compare', 'compareAttribute'=>'senha_confirma', 'message'=>"As senhas informadas são diferentes"),
		);
	}

	public function relations() {
		return array(
			'moduloDownloads' => array(self::HAS_MANY, 'ModuloDownload', 'idusuario'),
			'perfil' => array(self::BELONGS_TO, 'Perfil', 'idperfil'),
			'usuarioRecuperasenhas' => array(self::HAS_MANY, 'UsuarioRecuperasenha', 'idusuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idusuario' => Yii::t('app', 'Idusuario'),
			'idperfil' => null,
			'nome' => Yii::t('app', 'Nome'),
			'cpf' => Yii::t('app', 'CPF'),
			'email' => Yii::t('app', 'E-mail'),
			'telefone' => Yii::t('app', 'Telefone'),
			'senha' => Yii::t('app', 'Senha'),
			'senha_confirma' => Yii::t('app', 'Confirme a Senha'),
			'ativo' => Yii::t('app', 'Ativo'),
			'moduloDownloads' => null,
			'perfil' => null,
			'usuarioRecuperasenhas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idusuario', $this->idusuario);
		$criteria->compare('idperfil', $this->idperfil);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('cpf', $this->cpf, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('senha', $this->senha, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
