<?php

/**
 * This is the model base class for the table "modulo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Modulo".
 *
 * Columns in table "modulo" available as properties of the model,
 * followed by relations of table "modulo" available as properties of the model.
 *
 * @property integer $idmodulo
 * @property string $nome
 * @property string $url
 * @property integer $posicao
 * @property string $descricao
 * @property string $ativo
 *
 * @property ModuloCategoria[] $moduloCategorias
 */
abstract class BaseModulo extends GxActiveRecord {
	
    
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'modulo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Modulo|Modulos', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('posicao', 'numerical', 'integerOnly'=>true),
			array('nome, url', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('descricao', 'safe'),
			array('nome, url, posicao, descricao, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idmodulo, nome, url, posicao, descricao, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'moduloCategorias' => array(self::HAS_MANY, 'ModuloCategoria', 'idmodulo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idmodulo' => Yii::t('app', 'Idmodulo'),
			'nome' => Yii::t('app', 'Nome'),
			'url' => Yii::t('app', 'Url'),
			'posicao' => Yii::t('app', 'Posicao'),
			'descricao' => Yii::t('app', 'Descricao'),
			'ativo' => Yii::t('app', 'Ativo'),
			'moduloCategorias' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idmodulo', $this->idmodulo);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('posicao', $this->posicao);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}