<?php

/**
 * This is the model base class for the table "modulo_subcategoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ModuloSubcategoria".
 *
 * Columns in table "modulo_subcategoria" available as properties of the model,
 * followed by relations of table "modulo_subcategoria" available as properties of the model.
 *
 * @property integer $idmodulo_subcategoria
 * @property integer $idcategoria
 * @property string $nome
 * @property string $url
 * @property integer $posicao
 * @property string $descricao
 * @property string $ativo
 *
 * @property ModuloArquivo[] $moduloArquivos
 * @property ModuloCategoria $moduloCategoria
 */
abstract class BaseModuloSubcategoria extends GxActiveRecord {



	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'modulo_subcategoria';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Subcategoria|Subcategorias', $n);
	}

	public static function representingColumn() {
		return array('nome');
	}

	public function rules() {
		return array(
			array('idcategoria', 'required'),
			array('idcategoria, posicao', 'numerical', 'integerOnly'=>true),
			array('nome, url', 'length', 'max'=>100),
			array('ativo', 'length', 'max'=>1),
			array('descricao', 'safe'),
			array('nome, url, posicao, descricao, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idmodulo_subcategoria, idcategoria, nome, url, posicao, descricao, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'moduloArquivos' => array(self::HAS_MANY, 'ModuloArquivo', 'idmodulo_subcategoria'),
			'moduloCategoria' => array(self::BELONGS_TO, 'ModuloCategoria', 'idcategoria'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idmodulo_subcategoria' => Yii::t('app', 'Idmodulo Subcategoria'),
			'idcategoria' => null,
			'nome' => Yii::t('app', 'Nome'),
			'url' => Yii::t('app', 'Url'),
			'posicao' => Yii::t('app', 'Posicao'),
			'descricao' => Yii::t('app', 'Descricao'),
			'ativo' => Yii::t('app', 'Ativo'),
			'moduloArquivos' => null,
			'moduloCategoria' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idmodulo_subcategoria', $this->idmodulo_subcategoria);
		$criteria->compare('idcategoria', $this->idcategoria);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('posicao', $this->posicao);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('ativo', $this->ativo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
